##Taller Numpy

Este cuaderno tiene como objetivo dar respuesta a la tarea propuesta sobre exploración de la librería Numpy, la cual es empleada para manejar conjuntos de datos, también conocidos como "arreglos" o "arrays". Se usa como base el cuaderno sugerido en el classroom del curso, pero se incluyen elementos adicionales.

A continuación se carga la librería correspondiente.

In [1]:
import numpy as np

Para la creación de arreglos de distintas dimensiones se pueden usar números, listas o tuplas. el comando para asignar el objeto como un arreglo será "array". Notar que la dimensión estará determinada por la cantidad de paréntesis cuadrados que se incluyan en la definición de los objetos.

In [13]:
a = np.array(13)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print("a = ",a,"\n")
print("b = ",b,"\n")
print("c = ",c,"\n")
print("d = ",d,"\n")

a =  13 

b =  [1 2 3 4] 

c =  [[1 2 3 4]
 [5 6 7 8]] 

d =  [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



Se puede usar el comando ndim para verificar el número de dimensiones de cada arreglo.

In [14]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#Indexación básica
Se puede identificar el elemento que se encuentra en alguna posición específica del arreglo.

In [15]:
print("a =",a)
print("b[2] =",b[2])
print("c[1] =",c[1])
print("d[1] =",d[1])

a = 13
b[2] = 3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


In [18]:
print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("d[1,0,2] =",d[1,0,2])

a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


También se pueden imprimir fragmentos de los arreglos.

In [20]:
print(b[1:4])
print(c[1,1:3])

[2 3 4]
[6 7]


Se pueden incluir distintos tipos de datos como cadenas, booleanos o de punto flotante.

In [21]:
frutas = np.array(["Manzana", "Naranja", "Uva"])
print(frutas.dtype)

<U7


Se puede manipular el tipo de datos del arreglo dentro de la función de ccreación, siempre y cuando el cambio sea posible. Por ejemplo, podeos pasar de enteros a cadenas, pero no al sentido contrario.

In [22]:
number_to_string = np.array([6,1,2,4,623,8], dtype = 'S')
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [23]:
try:
  error_array = np.array(['a', '2', '3'],dtype = 'i')
except:
  print("Hay un error en su lógica")

Hay un error en su lógica


También se puede cambiar el tipo en arreglos ya existentes

In [33]:
floating_array = np.array([1.1, 2.1, 3.1])

int_array = floating_array.astype('i')
print(int_array)

[1 2 3]


##Forma de los arreglos
La forma se define como el número de elementos de la dimensión

In [34]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(4,)
(2, 4)
(2, 2, 4)


#Reformar arreglos
Se puede cambiar la forma de los arreglos usando el comando reshape. Esto es, cambiar el número de dimensiones o el número de elementos en cada dimensión.

In [38]:
print("c = ",c,"\n")
c_1D = c.reshape(1,8)
print("c_1D =",c_1D,"\n")
c_4D = c.reshape(4,2)
print("c_4D =",c_4D,"\n")

c =  [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



Se pueden hacer los cambios de dimensiones que se deseen siempre y cuando los valores establecidos coincidan con la cantidad de elementos.

In [39]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


d es un arreglo con 16 elementos, así que se pueden hacer reformas en las siguientes dimensiones 1x16, 4x4, 8x2, 2x4x2, entre otras.

In [40]:
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

Hay un error en sus operaciones


In [41]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

Si no se conocen las dimensiones de los arreglos, se puede definir un ajuste automático. En este caso, Numpy define el tamaño que considere más adecuado.

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Incluir -1 en la definición del reshape permite "aplanar" el arreglo a una sola dimensión.

In [43]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Para transponer un arreglo se una el comando T.

In [45]:
print("c =",c,"\n")
print("c.T =",c.T)
print("d =",d,"\n")
print("d.T =",d.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]
d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.T = [[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


# Iterar arreglos
Se pueden emplear los métodos tradicionales para realizar iteraciones de los arreglos definidos.

In [46]:
for x in d:
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


Si se desea iterar cada elemento, se necesita incluir la sentencia for para cada dimensión.

In [48]:
for x in d:
  for y in x:
    for z in y:
      print(z)

for e in d:
  for f in e:
    print(f)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


Sin embargo, en arreglos de gran tamaño, lo anterior puede resultar complicado o poco práctico. Por ello, numpy, cuenta con la función nditer().

In [49]:
for x in np.nditer(d):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


#Aplicar operaciones entre arreglos
numpy toene sus propias formas de aplicar operaciones:

#Suma

numpy tiene dos funciones, add() y sum(). El primero se aplica entre argumentos, el segundo se aplica en n elementoss para que se haga la suma, es necesairo que ambos arreglos tengan la misma forma.

In [52]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[6,5,4],
                 [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [53]:
arr3 = np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


Si se aplica un eje en sum(), se aplica la suma en ese mismo eje. Por ejemplo, con eje 0, se obtienen los mismos resultados que add().

In [54]:
np.sum([arr1, arr2, arr3],axis = 0)

array([[8, 8, 8],
       [8, 8, 8]])

In [59]:
np.sum([arr1, arr2, arr3],axis = 1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

#Multiplicación
El primer caso de multiplicación es prod(), que funciona similar a sum()

In [61]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


#Multiplicación matricial
Para la multiplicación de matrices se usa matmul() o dot(). Hay que tener en cuenta la forma de las matrices.

In [62]:
np.matmul(arr1,arr2.T)

array([[28, 10],
       [73, 28]])

In [63]:
np.dot(arr1,arr2.T)

array([[28, 10],
       [73, 28]])

In [64]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [65]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



matmul no realiza multiplicaciones de matrices con escaleres, en cambio, hace las multiplicaciones matriz a matriz. dot, toma los números dentro de las matrices como elementos.

In [66]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])